### PR TITLE
Add a two line prompt option

### PR DESCRIPTION
**Pull request by jmegs**
Loving this prompt as I explore fish, but I work in super long directories 
so wanted a second line.

This adds a boolean flag `hydro_two_line_prompt`. If that is true, inserts a
newline before the prompt character.

### CODE REVIEW

**Comment by stephantabor** [comment]
This doesn't handle the case where there's an error in `$pipestatus`, which I think would be unexpected for end users. 

Here's an example (I've added some additional spacing to my personal config to account for the vi mode status char)

image

A potential solution is to just add the user's normal prompt icon on a second line

image

**Comment by jmegs** [comment]
So like I said I am brand new to writing `fish` but I think I got this working by storing the error display text fragment in a variable and adding that the conditional that decides whether to display the newline.

I feel like there might be a more elegant or idiomatic `fish` way to do it, but this does seem to solve the issue @stephantabor  brought up

CleanShot 2021-11-15 at 15 44 46

**Comment by mattmc3** [comment]
@jmegs - This is a great addition. I've built on your idea and added some enhancements in a separate PR: https://github.com/jorgebucaran/hydro/pull/25

**Comment by mattmc3** [comment]
Vote to close as https://github.com/jorgebucaran/hydro/pull/25 was merged.

**Comment by jorgebucaran** [comment]
Hi, @jmegs, I've merged #25. If it's not too late, I'd love to hear your thoughts on that implementation and how it compares to yours here.

**Comment by jmegs** [comment]
just tested it out and looks great! closing this issue. like I said I am a total fish n00b and @mattmc3's implementation looks great to me

**Pull request closed without merging**
